name: prism24
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.33.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1   
  lottie: 3.3.1
  equatable: 2.0.7
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  shared_preferences: 2.5.3
  package_info_plus: ^8.3.0
  get: ^4.6.5
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/tiles/
    - assets/images/icons/
    - assets/images/powerups/
    - assets/images/ui/
    - assets/animations/
    - assets/audio/
    - assets/animations/confetti_win.json
    - assets/animations/fail_shake.riv

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
