// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeK5OjaQihIShgjKeMzvttksrC-lEQhqs',
    appId: '1:1057866169030:web:dca3108384b6bd1e0a35c7',
    messagingSenderId: '1057866169030',
    projectId: 'prisma24-812c8',
    authDomain: 'prisma24-812c8.firebaseapp.com',
    storageBucket: 'prisma24-812c8.firebasestorage.app',
    measurementId: 'G-VQ8HGT7TQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYR-JQLxB4aAa8u-ViRVbruE4pecFXjk',
    appId: '1:1057866169030:android:6e1f4344bdd7a0660a35c7',
    messagingSenderId: '1057866169030',
    projectId: 'prisma24-812c8',
    storageBucket: 'prisma24-812c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc7z6hrGCUpxN4Cty2Gy5lQIr2HHMTyQQ',
    appId: '1:1057866169030:ios:0290b4a28ca009fd0a35c7',
    messagingSenderId: '1057866169030',
    projectId: 'prisma24-812c8',
    storageBucket: 'prisma24-812c8.firebasestorage.app',
    iosBundleId: 'com.example.prism24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc7z6hrGCUpxN4Cty2Gy5lQIr2HHMTyQQ',
    appId: '1:1057866169030:ios:0290b4a28ca009fd0a35c7',
    messagingSenderId: '1057866169030',
    projectId: 'prisma24-812c8',
    storageBucket: 'prisma24-812c8.firebasestorage.app',
    iosBundleId: 'com.example.prism24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeK5OjaQihIShgjKeMzvttksrC-lEQhqs',
    appId: '1:1057866169030:web:d85440176fb5d8020a35c7',
    messagingSenderId: '1057866169030',
    projectId: 'prisma24-812c8',
    authDomain: 'prisma24-812c8.firebaseapp.com',
    storageBucket: 'prisma24-812c8.firebasestorage.app',
    measurementId: 'G-YHFHJVRKHD',
  );
}
